kind: pipeline
name: run-build

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: stronglytyped/arm-none-eabi-gcc
  commands:
  - cd build
  - ln -s /work/gcc-arm-none-eabi-8-2019-q3-update/ /usr/local/gcc-arm
  - make clean
  - make